### ISSUE TITLE
Dynamic loading frontc fails

### ISSUE THREAD

**Issue by anwarmamat** [BinaryAnalysisPlatform/FrontC#14]
I am trying to load frontc dynamically. If I compile native, it shows this error:
```
Warning 58: no `cmx` file was found in path for module `Frontc`, and its interface was not compiled with `-opaque`
```
When execute, it fails with this error:
```
Error during dynlink: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_dll "Failure(\"/path/bar.cmxs: undefined symbol: camlFrontc\")")
```
If I compile byte, it compiles, but when I run,
```
Error during dynlink: this object file uses unsafe features
```

**Comment by ivg** [comment]
The cmx warning is irrelevant, but we can and will fix it, thanks for reporting! The second issue is on dune side, reported in ocaml/dune#4552 
And the last problem could be resolved with `Dynlink.allow_unsafe_modules true`
