### ISSUE TITLE
Fail parsing named type right after it is defined

### ISSUE THREAD

**Issue by roptat** [BinaryAnalysisPlatform/FrontC#23]
Hi,

from latest master, I'm having issues with a file that defines a new type and uses it right after it:

```c
typedef struct my_t {
  int foo;
} my_t;
my_t bar();
```
gives me a parsing error on `my_t` on the last line. However:

```c
typedef struct my_t {
  int foo;
} my_t;
int baz();
my_t bar();
```
gives no parsing error

**Comment by ivg** [comment]
Did you have the same problem on older versions of FrontC? If yes, then can you tell what was the last working version?

**Comment by roptat** [comment]
a313b21ebc589248f6a8a2941ed9a54cd7c20e4f (v3.4.3) is the last commit that works for me. c5b8ab5ce95cb82014a71cef3382f969b0763d6b, the following commit has the parsing error with the above example.

**Comment by ivg** [comment]
I see that is bad :( It is the result of switching to menhir. FrontC is using a mutable state to maintain the set of types in the lexer and it looks like that menhir is prefetching the next token without actually finishing parsing the previous one. I am trying to investigate this issue.
