### ISSUE TITLE
anonymous union and struct

### ISSUE THREAD

**Issue by roptat** [BinaryAnalysisPlatform/FrontC#29]
Hi,

now that the previous issues are fixed, I have more :D. This time, it's about anonymous structs and unions:

```c
struct Scope {
    // Anonymous union
    union {
        char alpha;
        int num;
    };
};

struct Scope2
{
    // Anonymous structure
    struct
    {
        char alpha;
        int num;
    };
};
```

both structs have a parsing error, because a field is supposed to be a type with names, but the inner union and struct do not have a name. This is apparently part of C11, and also a GNU extension (in the file I have, the anonymous union is even preceded by `__extension__`). I tried applying the attached patch, but ctoxml gives me back empty structs:

```xml
<file>
	<struct id="struct:Scope"/>
	<struct id="struct:Scope2"/>
</file>
```

[anonymous-union-structs.patch](https://github.com/BinaryAnalysisPlatform/FrontC/files/6475156/frontc-1.txt)

**Comment by ivg** [comment]
> now that the previous issues are fixed, I have more :D

Damn, I was hoping to close all issues today :D But yes, I already saw, though I was thinking that the `__extension__` was the culprit. It is from `thread-shared-types.h`, right?
