### ISSUE TITLE
Syntax error on enums with trailing comma

### ISSUE THREAD

**Issue by correct-chris** [BinaryAnalysisPlatform/FrontC#3]
Frontc can't parse enums which have a trailing comma after the last variant.

```c
// enum-commas.c
typedef enum {
  Little,
  Medium,
  Big,
} Size;
```

Calling `parse_file` prints the error message `enum-commas.c[5] Syntax error: } Size;`.

**Comment by ivg** [comment]
Yep, the trailing comma was added in C99, which is not supported by FrontC.  PR #4 fixes this. 

If you're using opam, then until the fix reaches opam, consider using 
```
opam pin frontc --dev-repo
```

**Comment by ivg** [comment]
for the reference: https://github.com/ocaml/opam-repository/pull/14290
