### ISSUE TITLE
designated initializer style

### ISSUE THREAD

**Issue by roptat** [BinaryAnalysisPlatform/FrontC#32]
Sorry, here's another one :D

```c
struct point {
  int    x;
  int    y;
};

int main() {
  struct point p = { .y = 2, .x = 1 };
}
```
fails to parse the initialization of variable p.

designated initializer style is a C99 feature.

**Comment by ivg** [comment]
Yeah, that's the syntax I always found myself hard to grasp) Do you plan to work on it?

**Comment by roptat** [comment]
I'll give it a try

**Comment by ivg** [comment]
Awesome, I meantime, added more tests. With that said, could you please include tests in your next patch? It is easy with [dune cram][1], just take the code you examples and put into `ctoxml/test.t/c99-struct-initializers.c` and add the following line to `ctoxml/test.t/run.t` (notice a pair of spaces before $, they are important)

```
  $ ctoxml c99-struct-initializers.c
```

Then run `dune test` and it will spill the diff saying that there is a change in the tests, review if the  output matches your expectations, and once it does, just do
```
dune promote
```

to accept this output. 

[1]: https://dune.readthedocs.io/en/stable/tests.html#cram-tests
